repos:
-   repo: https://github.com/python/black
    rev: 19.10b0
    hooks:
    -   id: black
        language_version: python3
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.7
    hooks:
    -   id: flake8
        language: python_venv
        additional_dependencies: [flake8-comprehensions>=3.1.0]
    -   id: flake8
        name: flake8-pyx
        language: python_venv
        files: \.(pyx|pxd)$
        types:
          - file
        args: [--append-config=flake8/cython.cfg]
    -   id: flake8
        name: flake8-pxd
        language: python_venv
        files: \.pxi\.in$
        types:
          - file
        args: [--append-config=flake8/cython-template.cfg]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
        language: python_venv
        exclude: ^pandas/__init__\.py$|^pandas/core/api\.py$
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.730
    hooks:
     -  id: mypy
        args:
          # As long as a some files are excluded from check-untyped-defs
          # we have to exclude it from the pre-commit hook as the configuration
          # is based on modules but the hook runs on files.
          - --no-check-untyped-defs
          - --follow-imports
          - skip
        files: pandas/
